[package]
name = "HTTPiper"
version = "0.1.0"
authors = ["Andrea Tupini <tupini07@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.1.2"
pest_consume = "1.0.2"
pest_derive = "2.1.0"